replicaCount: 2

image:
  repository: acreusdev01.azurecr.io/sample-python-app
  pullPolicy: IfNotPresent
  tag: a37aadb90befa274f19d6b248cdd3fbeda850f96
containerPort: 8000
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: Ingress
  annotations: {}
  tls: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5